//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grocery
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public int user_info_id { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
